"""Setting up tables

Revision ID: 5fb309e1b756
Revises: 
Create Date: 2022-03-19 14:48:01.855774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb309e1b756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('floor_price', sa.Float(precision=10, asdecimal=5), nullable=True),
    sa.Column('count', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('discord_user',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user__id', sa.Integer(), nullable=True),
    sa.Column('set_nft_channel_name', sa.String(length=64), nullable=True),
    sa.Column('set_nft_channel_id', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('server_id', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user__id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('one_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_supply', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('count', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('num_owners', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('num_reports', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('market_cap', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('floor_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_user',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('chat_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('seller_address', sa.String(length=256), nullable=True),
    sa.Column('buyer_address', sa.String(length=256), nullable=True),
    sa.Column('marketplace_address', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(precision=10, asdecimal=5), nullable=True),
    sa.Column('block_timestamp', sa.String(length=256), nullable=True),
    sa.Column('block_number', sa.String(length=256), nullable=True),
    sa.Column('block_hash', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_collection',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collection')
    op.drop_table('transaction')
    op.drop_table('telegram_user')
    op.drop_table('history')
    op.drop_table('discord_user')
    op.drop_table('user')
    op.drop_table('collection')
    # ### end Alembic commands ###
